### ISSUE TITLE
onFIXMessage function is useful?

### ISSUE THREAD

**Issue by shrimpceviche** [DatName/FIX.jl#1]
Greeting, sorry that I couldn't find a better place to ask questions. I went through the FIX.jl carefully, and plan to make a pr to update the library to Julia 1.5+. However, I am trying to understand what onFIXMessage does aside from throwing errors, which seems to be invoked for any incoming message on line 171 of the FIX.jl code. Thank you.

**Comment by DatName** [comment]
Hi.
`onFIXMessage` is used to give user control over how he want to handle incoming messages. I just updated readme (last part of `Usage`  section) to give you an example

**Comment by shrimpceviche** [comment]
Thanks! Appreciate it :)
